############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Project"
url = "project/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4
hasChildren = true

  [[main]]
  parent = "Blog"
  name = "Vanlife"
  url = "blog/"
  weight = 1

  [[main]]
  parent = "Blog"
  name = "Hiking"
  url = "blog/"
  weight = 2

  [[main]]
  parent = "Blog"
  name = "Veganism"
  url = "blog/"
  weight = 3
  
  [[main]]
  parent = "Blog"
  name = "Climate Change"
  url = "blog/"
  weight = 4

# footer menu
[[footer]]
name = "Home"
url = ""
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3