---
baseurl: https://atomsofus.com/
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Atoms of Us
languages:
  en:
    languageName: English
    title: Atoms of Us
    weight: 1
  zh-cn:
    languageName: 中文
    title: 演示站点
    weight: 2
  ar:
    languageName: عربي
    languagedirection: rtl
    title: موقع تجريبي
    weight: 3
disqusShortname: hugo-theme-stack
googleAnalytics: 
DefaultContentLanguage: en
hasCJKLanguage: false
permalinks:
  post: "/p/:slug/"
  page: "/:slug/"
params:
  mainSections:
  - post
  featuredImageField: image
  rssFullContent: true
  favicon: 
  footer:
    since: 2022
    customText: 
  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST
  sidebar:
    subtitle: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    avatar:
      enabled: true
      local: true
      src: "/img/avatar.jpg"
  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0
  comments:
    enabled: true
    provider: disqus
    disqusjs:
      shortname: 
      apiUrl: 
      apiKey: 
      admin: 
      adminLabel: 
    utterances:
      repo: 
      issueTerm: pathname
      label: 
    remark42:
      host: 
      site: 
      locale: 
    vssue:
      platform: 
      owner: 
      repo: 
      clientId: 
      clientSecret: 
      autoCreateIssue: false
    waline:
      serverURL: 
      lang: 
      pageview: 
      emoji:
      - https://unpkg.com/@waline/emojis@1.0.1/weibo
      requiredMeta:
      - name
      - email
      - url
      locale:
        admin: Admin
        placeholder: 
    twikoo:
      envId: 
      region: 
      path: 
      lang: 
    cactus:
      defaultHomeserverUrl: https://matrix.cactus.chat:8448
      serverName: cactus.chat
      siteName: ''
    giscus:
      repo: 
      repoID: 
      category: 
      categoryID: 
      mapping: 
      lightTheme: 
      darkTheme: 
      reactionsEnabled: 1
      emitMetadata: 0
    gitalk:
      owner: 
      admin: 
      repo: 
      clientID: 
      clientSecret: 
    cusdis:
      host: 
      id: 
  widgets:
    homepage:
    - type: search
    - type: archives
      params:
        limit: 5
    - type: categories
      params:
        limit: 10
    - type: tag-cloud
      params:
        limit: 10
    page:
    - type: toc
  opengraph:
    twitter:
      site: 
      card: summary_large_image
  defaultImage:
    opengraph:
      enabled: false
      local: false
      src: 
  colorScheme:
    toggle: true
    default: auto
  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true
menu:
  social:
  - url: https://twitter.com
    name: Twitter
    params:
      icon: brand-twitter
    weight: 1
    identifier: twitter
  - url: https://github.com/CaiJimmy/hugo-theme-stack
    name: GitHub
    params:
      icon: brand-github
    weight: 2
    identifier: github
related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
  - name: tags
    weight: 100
  - name: categories
    weight: 200
markup:
  goldmark:
    renderer:
      unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
